version: "2"
# linters-settings:
  
linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dogsled
    - gocognit
    - goconst
    - gocritic
    - godox
    - gosec
    - nakedret
    - unconvert
    - unparam
    - whitespace
    - dupl
    - misspell
    - revive
  disable:
    - errcheck
  settings:
    govet:
      check-shadowing: false
      settings:
        printf:
          funcs: # TODO:
          # - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
    golint:
      min-confidence: 0
    gocyclo:
      min-complexity: 15
    maligned:
      suggest-new: true
    revive:
      directives:
        - name: specify-disable-reason
          severity: error
      rules:
        - name: exported
          disabled: true
        - name: add-constant
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - max-lit-count: "3"
              allow-strs: '""'
              allow-ints: "0,1,2,10,64,16,32"
              allow-floats: "0.0,0.,1.0,1.,2.0,2."
        - name: call-to-gc
          severity: warning
          disabled: false
          exclude: [""]
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#cognitive-complexity
        - name: cognitive-complexity
          severity: warning
          disabled: false
          exclude: [""]
          arguments: [ 15 ]
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#confusing-naming
        - name: confusing-naming
          severity: warning
          disabled: false
          exclude: [""]
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#confusing-results
        - name: confusing-results
          severity: warning
          disabled: false
          exclude: [""]
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#constant-logical-expr
        - name: constant-logical-expr
          severity: warning
          disabled: false
          exclude: [""]
    dupl:
      threshold: 100
    misspell:
      locale: US
    lll:
      line-length: 140
    gocritic: # TODO:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain # TODO
        - octalLiteral # TODO
        - whyNoLint # TODO
        - wrapperFunc # TODO
        - paramTypeCombine
        - hugeParam
        - rangeValCopy
    gomnd:
      settings:
        mnd:
          # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
          checks: argument,case,condition,operation,return,assign
    funlen:
      lines: 100
      statements: 50
    godox:
      keywords:
        - OPTIMIZE # marks code that should be optimized before merging
        - FIXME # marks code that should be fixed before merging
        - HACK # marks hack-arounds that should be removed before merging
    gosec:
      excludes:
        - G115

  exclusions:
    generated: lax
    warn-unused: true
    rules:
      - path: main\.go
        linters:
          - revive
      - path: config\.go
        linters:
          - revive
      - path: _test\.go
        linters:
          - gomnd
          - gocritic
          - dupl
          - unparam
          - gosec
          - revive

run:
  go: "1.24"