linters-settings:
  govet:
    check-shadowing: false
    settings:
      printf:
        funcs: # TODO:
        # - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/lodthe/aws-ec2-telegram-bot
  gocritic: # TODO:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain # TODO
      - octalLiteral # TODO
      - whyNoLint # TODO
      - wrapperFunc # TODO
      - paramTypeCombine
      - hugeParam
      - rangeValCopy
  gomnd:
    settings:
      mnd:
        # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
        checks: argument,case,condition,operation,return,assign
  funlen:
    lines: 100
    statements: 50
  godox:
    keywords:
      - OPTIMIZE # marks code that should be optimized before merging
      - FIXME # marks code that should be fixed before merging
      - HACK # marks hack-arounds that should be removed before merging

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - dogsled
    - gocognit
    - goconst
    - gocritic
    - godox
    - gofmt
    - goimports
    - golint
    - gosec
    - nakedret
    - exportloopref
    - unconvert
    - unparam
    - whitespace
    - dupl
    - misspell

run:
  skip-dirs:
    - .infra
issues:
  exclude-rules:
    - linters:
        - gomnd
      text: "Magic number: 1,"
    - path: _test\.go
      linters:
        - gomnd
        - gocritic
        - golint
        - gosec
        - unparam

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.45.1 # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"