# The default config location is 'config.yaml', but it can be overridden via CONFIG_PATH env.

# [OPTIONAL] Log redundancy level. Default: debug.
# Available log levels: trace (all), debug, info, warn, error, fatal, disabled.
log_level: info

# ClickHouse Docker image configuration.
docker_image:
  image: clickhouse/clickhouse-server
  os: linux
  architecture: amd64

  # [OPTIONAL] How often available image tags will be fetched from dockerhub.
  image_tags_cache_expiration_time: 3m

# Rest API configuration.
api:
  # [OPTIONAL] Server listening address. Default: :9000.
  address: :9000

  # [OPTIONAL] Request processing timeout. Default: 60s.
  server_timeout: 60s

# [OPTIONAL] Prometheus metrics export address. Default: :2112.
prometheus_address: :2112

aws:
  # AWS credentials. Also, you can set them via AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envs.
  access_key_id: key_id
  secret_access_key: secret

  region: us-east-2

  # DynamoDB table name used to store completed query runs.
  query_runs_table: QueryRuns

# [OPTIONAL] Absolute path to the custom config used on clickhouse-server startup.
# custom_config_path: /fast-startup-config.xml

runner:
  # Available types: EC2, DOCKER_ENGINE.
  type: DOCKER_ENGINE

  # Required if type is EC2.
  ec2:
    # AWS EC2 instance id used to run queries.
    instance_id: i-023c5bb002bb45ad4

  # Required if type is DOCKER_ENGINE.
  docker_engine:
    # You can configure the garbage collector to prune hanged up containers and images.
    # If the field is missed, gc is disabled.
    # Default: gc is disabled.
    gc:
      # [OPTIONAL] How often the garbage collector should be triggered. Default: once a minute.
      trigger_frequency: 1m

      # Containers GC

      # [OPTIONAL] Containers created before (NOW() - TTL) are force removed.
      # Default: disabled (containers are not force removed).
      container_ttl: 1m

      # Images GC

      # Image gc triggers when there are at least image_count_threshold downloaded images.
      # Default: missed (images are not pruned).
      image_count_threshold: 50

      # # After the images garbage collection, at most image_buffer_size least recently tagged images will be left.
      # Default: 0 (all images are pruned).
      image_buffer_size: 30
